# performance_config.py
"""
Performance Configuration for AURA

Centralized configuration for all performance optimization settings.
"""

# Connection Pool Settings
CONNECTION_POOL_MAX_CONNECTIONS = 10
CONNECTION_POOL_MAX_RETRIES = 3
CONNECTION_POOL_BACKOFF_FACTOR = 1.0

# Image Cache Settings
IMAGE_CACHE_MAX_SIZE_MB = 100
IMAGE_CACHE_MAX_ENTRIES = 50
IMAGE_CACHE_EXPIRY_SECONDS = 300  # 5 minutes

# Parallel Processing Settings
PARALLEL_MAX_WORKERS = 4
PARALLEL_ENABLE_IO_PARALLELIZATION = True
PARALLEL_ENABLE_CPU_PARALLELIZATION = True
PARALLEL_PERCEPTION_REASONING = True

# Performance Monitoring Settings
PERFORMANCE_MAX_METRICS = 1000
PERFORMANCE_SYSTEM_MONITORING_INTERVAL = 30  # seconds
PERFORMANCE_GARBAGE_COLLECTION_INTERVAL = 300  # seconds

# Optimization Thresholds
MEMORY_WARNING_THRESHOLD_MB = 500
MEMORY_CRITICAL_THRESHOLD_MB = 1000
CPU_WARNING_THRESHOLD_PERCENT = 80
CPU_CRITICAL_THRESHOLD_PERCENT = 95

# Cache Hit Rate Targets
TARGET_CACHE_HIT_RATE_PERCENT = 70
TARGET_API_RESPONSE_TIME_MS = 2000

# Compression Settings
IMAGE_COMPRESSION_QUALITY = 85
IMAGE_MAX_DIMENSION = 1920
IMAGE_OPTIMIZATION_ENABLED = True

# API Optimization Settings
API_REQUEST_TIMEOUT_SECONDS = 30
API_CONNECTION_TIMEOUT_SECONDS = 10
API_READ_TIMEOUT_SECONDS = 30
API_RETRY_DELAY_SECONDS = 2.0

# Performance Logging
PERFORMANCE_LOG_LEVEL = "INFO"
PERFORMANCE_LOG_DETAILED_METRICS = False
PERFORMANCE_LOG_SYSTEM_METRICS = True

# Feature Flags
ENABLE_CONNECTION_POOLING = True
ENABLE_IMAGE_CACHING = True
ENABLE_PARALLEL_PROCESSING = True
ENABLE_PERFORMANCE_MONITORING = True
ENABLE_AUTOMATIC_OPTIMIZATION = True

# Automatic Optimization Settings
AUTO_OPTIMIZE_CACHE_SIZE = True
AUTO_OPTIMIZE_THREAD_COUNT = True
AUTO_OPTIMIZE_COMPRESSION_QUALITY = True
AUTO_OPTIMIZE_RETRY_STRATEGY = True

# Resource Limits
MAX_CONCURRENT_API_REQUESTS = 5
MAX_CACHED_IMAGES = 50
MAX_THREAD_POOL_SIZE = 8
MAX_PROCESS_POOL_SIZE = 4

# Monitoring Intervals
HEALTH_CHECK_INTERVAL_SECONDS = 60
METRICS_COLLECTION_INTERVAL_SECONDS = 30
RESOURCE_CLEANUP_INTERVAL_SECONDS = 300

# Performance Targets
TARGET_SCREEN_CAPTURE_TIME_MS = 500
TARGET_VISION_ANALYSIS_TIME_MS = 3000
TARGET_REASONING_TIME_MS = 5000
TARGET_AUTOMATION_ACTION_TIME_MS = 200

# Quality vs Performance Trade-offs
PREFER_QUALITY_OVER_SPEED = False
ENABLE_AGGRESSIVE_CACHING = True
ENABLE_PREDICTIVE_CACHING = False
ENABLE_BACKGROUND_OPTIMIZATION = True